input MusicContentInput {
    privacySetting: MusicContentPrivacySetting

    type: MusicContentType

    title: String
    artist: String

    artworkS3Key: String

    primaryGenre: String
    secondaryGenre: String

    description: String

    upc: String
    ean: String
    isrc: String

    price: Int
    explicitContent: Boolean
    language: LanguageEnum

    position: Int

    tracks: [MusicContentInput!] # Get merged
}