type MusicContent implements Node {
    id: ID!
    createdAt: String!
    updatedAt: String
    soundCloudId: Int
    userId: String!
    privacySetting: MusicContentPrivacySetting

    type: MusicContentType!

    title: String!
    artist: String!

    artworkS3Key: String
    artworkUrl: String
    artworkVersions: [MusicContentFileVersion!]

    audioS3Key: String
    audioS3Url: String
    audioVersions: [MusicContentFileVersion!]

    primaryGenre: String
    secondaryGenre: String

    description: String
    status: MusicContentStatus

    duration: Int
    fileFormat: String
    fileSize: Int

    upc: String
    ean: String
    isrc: String

    price: Int
    explicitContent: Boolean
    language: LanguageEnum

    position: Int

    tracks: [MusicContent!]
    release: Release


}

type MusicContentFileVersion {
    size: Int!
    eTag: String!
    lastModified: String!
    versionId: String
    isLatest: Boolean!
    metadata: JSON
}

enum MusicContentType {
    TRACK
    ALBUM
}

enum MusicContentPrivacySetting {
    ANYONE
    OWNER_ONLY
}

enum MusicContentStatus {
  LIVE
  PROCESSING
  ISSUE
}