type Playlist implements Node {
    id: ID!
    createdAt: String!
    updatedAt: String

    soundCloudId: Int
    userId: String!

    type: PlaylistType!
    privacySetting: PlaylistPrivacySetting!

    title: String
    artist: String

    artworkS3Key: String
    artworkUrl: String

    description: String

    duration: Int
    upc: String

    tracks: [Track!]
    release: Release
}

enum PlaylistType {
    EP
    ALBUM
}

enum PlaylistPrivacySetting {
    ANYONE
    OWNER_ONLY
}