input TrackInput {
    privacySetting: TrackPrivacySetting

    title: String
    artist: String

    primaryGenre: String
    secondaryGenre: String

    description: String

    price: Int
    explicitContent: Boolean
    language: LanguageEnum
}