# Settings that can be changes by the user.

input ReleaseInput {
    defaultMetadata: ReleaseDefaultMetadataInput
    rightsHolder: ReleaseRightsHolderInput

    # Must be a whitelisted user.
    status: ReleaseStatusEnum
}

input ReleaseDefaultMetadataInput {
    title: String
    artist: String
    recordLabel: String
    language: String
    primaryGenre: String
    secondaryGenre: String
    releaseDate: String
    price: Int

    artworkVersionId: String
    audioVersionId: String
}

input ReleaseRightsHolderInput {
    firstName: String
    lastName: String
    address: String
    city: String
    state: String
    zipCode: String
    phoneNumber: String
    didAgree: Boolean
}