type User implements Node {
  id: ID!
  createdAt: String!
  updatedAt: String

  # Account
  email: String!
  phoneNumber: String
  # stripeCustomerId: String
  stripeCustomer: JSON
  soundCloudUserId: String
  soundCloudAccessToken: String

  # Profile
  avatarKey: String
  avatarUrl: String
  displayName: String
  city: String
  country: String
  blurb: String
}

input UserInput {
  # Account
  email: String!
  phoneNumber: String

  # Profile
  avatarKey: String
  displayName: String
  city: String
  country: String
  blurb: String
}