service: jamout-gql

frameworkVersion: ">=1.16.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  region: us-west-1
  memorySize: 128

functions:
  api:
    handler: handler.graphql
    events:
    - http:
        path: graphql
        method: post
        cors: true
        integration: lambda-proxy

resources: 
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1