# Chat channel type - chat subscriptions are joined within the resolver
type Channel {
  createdAt: String!,
  updatedAt: String,
  id: ID!
  type: String!
  name: String,
  messages: [Message!]!,
  ownerUserId: ID,
  users: [Profile!]!
}
