
enum ChannelType {
  DM
  GROUP
}

type Channel {
  createdAt: String!
  updatedAt: String
  id: ID!
  type: ChannelType!
  avatar: String!
  # Name is null if channel type === DM
  name: String
  lastMessage: Message
  messages: [Message!]!
  messageCount: Int
  # ownerId is null if the channel type === DM
  ownerId: String
  # If channel is assistant type then the only element is the user.
  users: [User!]!
  superPowers: [String]

  ### SUBSCRIPTION FIELDS ###
  lastRead: String
  unreadCount: Int
  mentionCount: Int
}

type Message {
	id: ID!
	createdAt: String!
	updatedAt: String!
  isBotChannel: Boolean
	channelId: String! # ID, 't', 'c', userID if isbot
	timestamp: String!
	senderId: ID!
  sender: User!
	action: String # Typing, Read Receipt, Disable Input
	type: String # Defaults to Text
	intialState: JSON # Current message state
	actions: [JSON!] # Playable actions
}

input ChannelInput {
  type: String!
  userIds: [ID!]!
  name: String
}

input MessageActionInput {
  channelId: ID!
  type: String!
  payload: JSON
}

input TextMessageInput {
  id: ID!
  isBotChannel: Boolean
  channelId: ID
  text: String!
}