# Me is a User object on steroids. Me typed objects can only be queried
# by the owner.
type Me {
  jwt: String
  createdAt: String!
  updatedAt: String
  id: ID!
  username: String!
  email: String!
  permalink: String!
  displayName: String!
  location: String
  avatarUrl: String
  connections: [Connection!]
  assistantChannel: Channel
  roles: [String!]
  permissions: [String!]
  context: MeContext
  acl: String # *, null, private
  premium: Premium # null or 
}

type MeContext {
  assistant: [JSON!]
  web: MeWebContext
}

type MeWebContext {
  role: String
}

type Premium {
  stripeId: String,
  createdAt: Int
}

input MeInput {
  id: ID!
  username: String
  permalink: String
  displayName: String
  location: String
  avatarKey: String
  context: MeContextInput
  acl: String
}

input MeContextInput {
  web: MeWebContextInput
}

input MeWebContextInput {
  role: String!
}
