type Mutation {
  # Authentication + Utils
  login(email: String!, password: String!): String!
  signUp(email: String!, username: String!, password: String!): String!
  verifyToken(token: String!): Boolean!
  generateS3Signature(stringToSign: String!, datetime: String!): String!
  # Chat
  openChannel(type: ChannelType!, users: [ID!]!): Channel
  sendInput(input: ChatInput!): Message # Most inputs should persist a message....
  updateAssistantContext(input: AssistantContextInput!): Boolean # null or true = success
  sendAssistantMessage(anonId: ID, input: AssistantMessageInput!): AssistantMessage!
  # Distribution
  createRelease(input: ReleaseInput!): Release
  updateRelease(id: ID!, input: ReleaseInput!): Release
  deleteRelease(id: ID!): ID!
  payForRelease(id: ID!, stripeToken: String!, saveSource: Boolean!): Release
}
