type Mutation {
  # Authentication + Utils
  login(email: String, password: String, scAccessToken: String): String!
  # signUp(email: String!, username: String!, password: String!): String!
  verifyToken(token: String!): Boolean!
  updateUser(input: UserInput!): User!
  generateS3Signature(stringToSign: String!, datetime: String!): String!
  upgradeToPremium(token: String!): User!

  # Distribution
  updateRelease(contentId: ID!, input: ReleaseInput!): Release!
}
