type Mutation {
  # Authentication + Utils
  login(email: String!, password: String!): String!
  signUp(email: String!, username: String!, password: String!): String!
  verifyToken(token: String!): Boolean!
  generateS3Signature(stringToSign: String!, datetime: String!): String!
  # Chat
  openChannel(type: ChannelType!, users: [ID!]!): Channel
  postback(input: ChatPostback!): Message # Postback might return a message... might.
  sendInput(input: ChatInput!): Message # Most inputs should persist a message....
  # Distribution
  createRelease(input: ReleaseInput!): Release
  createStudioEvent(type: String, nextEvent: StudioEventInput): StudioEvent
  updateRelease(id: ID!, input: ReleaseInput!): Release
  deleteRelease(id: ID!): ID!
  payForRelease(id: ID!, stripeToken: String!, saveSource: Boolean!): Release
  createMusicEvent(eventData: MusicEventInput): MusicEvent!
  createEventArtist(artistData: EventArtistInput): EventArtist!
  updateEventArtist(eventArtist: UpdateEventArtistInput!, response: String!): EventArtist!
}
