type Profile {
  jwt: String
  createdAt: String!
  updatedAt: String
  id: ID!
  userId: ID!
  username: String!
  permalink: String!
  displayName: String!
  location: String
  avatarKey: String
  avatarUrl: String
  connections: [Connection!]
  assistantChannel: Channel
}
