type Query {
  me: Me
  assistantChannel: Channel
  channels(excludeAssistant: Boolean, messageLimit: Int, channelId: ID): [Channel!]!
  messages(channelId: ID!, limit: Int): [Message!]!
  release(id: ID!): Release
  releases: [Release!]!
  user(id: ID, permalink: String, username: String): User!
  users: [User!]
  studioEvent: [[StudioEvent]]
  musicEvents: [MusicEvent]
  eventArtist(eventId: ID): [EventArtist]
  track(userId: ID, permalink: String): [Track]
}
