type Query {
  me: User!
  assistantChannel: Channel
  channels(excludeAssistant: Boolean, messageLimit: Int): [Channel!]!
  messages(channelId: ID!, limit: Int): [Message!]!
  release(id: ID!): Release
  releases: [Release!]!
  studioEvent: [[StudioEvent]]
  musicEvents: [MusicEvent]
  eventArtist(eventId: ID): [EventArtist]
  track(userId: ID): [Track]
}
