input ReleaseInput {
  type: ReleaseType,
  artworkS3Key: String,
  title: String,
  artist: String,
  recordLabel: String,
  language: String,
  primaryGenre: String,
  secondaryGenre: String,
  releaseDate: Int,
  albumPrice: Int,
  trackPrice: Int,
  tracklist: [ReleaseInputTrack!]
}

input ReleaseTrackInput {
  title: String
  primaryArtists: [String!]
  featuredArtists: [String!]
  position: Int
  explicit: Boolean
  s3Key: String
}
