
# A ReleaseTrack can return null for any properties as an upload can finish
# while an artist is still editing metadata. So, an s3Key might be set before
# a title is.
type ReleaseTrack {
  id: String!
  position: Int,
  primaryArtists: [String!],
  featuredArtists: [String!],
  title: String,
  explicit: Boolean,
  s3Key: String,
}
