type Release {
  id: ID!,
  status: ReleaseStatus!,
  userId: ID!,
  stripeOrderId: String,
  type: ReleaseType!,
  readableType: String!,
  artworkS3Key: String,
  artworkUrl: String,
  title: String,
  artist: String,
  recordLabel: String,
  language: String,
  primaryGenre: String,
  secondaryGenre: String,
  releaseDate: String,
  price: Int,
  tracklist: [ReleaseTrack!]
}
