type Track {
  id: ID!,
  userId: ID!,
  artworkKey: String,
  audioKey: String,
  type: String!,
  title: String!,
  playCount: Int
  audioUrl: String,
  artworkUrl: String,
  createdAt: String,
  user: User!
  featuredUsers: [User]
  privacySetting: TrackPrivacySetting!
  spotlight: Boolean
}


enum TrackPrivacySetting {
  PRIVATE
  CONNECTIONS_ONLY
  PUBLIC
}

input TrackInput {
  artworkKey: String,
  audioKey: String,
  type: String,
  title: String!,
  featuredUserIds: [String!]
  privacySetting: TrackPrivacySetting
}