type Track {
  id: ID!,
  userId: ID!,
  artworkKey: String,
  audioKey: String,
  type: String!,
  title: String!,
  playCount: Int
  audioUrl: String,
  artworkUrl: String,
  createdAt: String,
  user: TrackUser
  spotlight: Boolean
}

type TrackUser {
  userId: ID,
  displayName: String
}

