type User {
  createdAt: String!
  updatedAt: String
  id: ID!
  username: String!
  permalink: String!
  displayName: String!
  location: String
  avatarKey: String
  avatarUrl: String
  connections: [Connection!]
  # Defines whether or not the current user is connected to this user.
  connected: ConnectionStatus,
  acl: String,
  tracks: [Track!]
}
