type User {
  createdAt: String!
  updatedAt: String
  id: ID!
  displayName: String
  city: String
  country: String
  blurb: String
  email: String
  phoneNumber: String
  avatarUrl: String
  scOauthToken: String
}
